name: tpm2-simulator-chrisccoulson
version: '0.1.0'
summary: TPM 2.0 Reference Simulator
description: |
  This is a TPM 2.0 simulator based on the official TCG rerefence
  implementation of the TPM 2.0 specification.
base: core18
architectures:
  - build-on: amd64

apps:
  tpm2-simulator:
    command: usr/bin/tpm2-simulator
    plugs:
      - network-bind

parts:
  ms-tpm-20-ref:
    source: https://github.com/microsoft/ms-tpm-20-ref.git
    source-commit: 69437ff7622a0110ac2088fca5ae9bb265c0fb1c
    plugin: autotools
    build-packages:
      - autoconf-archive
      - libssl-dev
      - pkg-config
    override-pull: |
      snapcraftctl pull
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patches/store-nvchip-in-snap-user-common.patch
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patches/wait-for-remote-close.patch
    override-build: |
      cd TPMCmd
      ./bootstrap
      ./configure --prefix=/usr
      make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
