name: tpm2-simulator-chrisccoulson
version: '1.83.0'
summary: TPM 2.0 Reference Simulator
description: |
  This is a TPM 2.0 simulator based on the official TCG rerefence
  implementation of the TPM 2.0 specification.
base: core18
architectures:
  - build-on: amd64

apps:
  tpm2-simulator:
    command: usr/bin/tpm2-simulator
    plugs:
      - home
      - network-bind

parts:
  ms-tpm-20-ref:
    source: https://github.com/chrisccoulson/ms-tpm-20-ref.git
    source-commit: 7603b835bb9635a0012286d57ddc8bf716ea5457
    plugin: autotools
    build-packages:
      - autoconf-archive
      - libssl-dev
      - pkg-config
    override-build: |
      cd TPMCmd
      ./bootstrap
      ./configure --prefix=/usr
      make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
